services:
  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: S3cret
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: S3cret
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mariadb-data:
